name: "apkdiff"
description: "Signal-Android apkdiff script as a reusable action."
inputs:
  APKS_A:
    required: true
    description: "First set of APK files to compare."
  APKS_B:
    required: true
    description: "Second set of APK files to compare."
  IGNORE_FILES:
    required: false
    description: "List of files to ignore during comparison."

runs:
  using: composite
  steps:
    - name: Exclude some known different (but acceptable) files
      shell: bash
      run: |
        set -xeuo pipefail
        mapfile -t IGNORE_FILES <<< "${{ inputs.IGNORE_FILES }}"
        mapfile -t APKS_A <<< "${{ inputs.APKS_A }}"
        mapfile -t APKS_B <<< "${{ inputs.APKS_B }}"
        for file in "${IGNORE_FILES[@]}"; do
          for apk in "${APKS_A[@]}"; do
            zip -d "$apk" "$file" || true
          done
          for apk in "${APKS_B[@]}"; do
            zip -d "$apk" "$file" || true
          done
        done
    - name: aapt
      shell: bash
      run: echo "PATH=/usr/local/lib/android/sdk/build-tools/37.0.0:$PATH" >> $GITHUB_ENV
    - name: Verify
      shell: bash
      run: |
        set -xeuo pipefail
        pip install uv
        git clone https://github.com/signalapp/Signal-Android --depth 1 actions_apkdiff
        cd actions_apkdiff/reproducible-builds/apkdiff
        uv sync

        mapfile -t APKS_A <<< "${{ inputs.APKS_A }}"
        mapfile -t APKS_B <<< "${{ inputs.APKS_B }}"
        for i in "${!APKS_A[@]}"; do
          uv run apkdiff.py "../../../${APKS_A[$i]}" "../../../${APKS_B[$i]}"
        done
