name: Briar-Android

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

jobs:
  website-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Dockerfile
        run: |
          sudo apt update && sudo apt install -y fuse
          git clone https://github.com/BarbossHack/briar-reproducer -b barboss-hack-update-reproducer --depth 1
          docker build -t briar/reproducer briar-reproducer
      - name: Reproducible
        run: |
          sudo docker run --privileged --device /dev/fuse --name reproducer briar/reproducer:latest ./reproduce.py briar release-${{ inputs.VERSION }}
          sudo docker cp reproducer:/opt/briar-reproducer/briar/briar-android/build/outputs/apk/official/release/briar-android-official-release-unsigned.apk build.apk
          sudo docker cp reproducer:/opt/briar-reproducer/briar-${{ inputs.VERSION }}.apk official.apk
          sudo chmod 666 *.apk
      - name: Signal Apkdiff
        run: |
          pip install uv
          git clone https://github.com/signalapp/Signal-Android --depth 1
          cd Signal-Android/reproducible-builds/apkdiff
          uv sync
          zip -d ../../../official.apk "META-INF/*"
          zip -d ../../../build.apk "META-INF/*"
          uv run apkdiff.py ../../../official.apk ../../../build.apk

  notify:
    needs: [website-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
