name: cron

on:
  push:
    paths:
      - ".github/workflows/cron.yml"
  schedule:
    - cron: "0 3 * * *" # every day 03:00 am UTC
  workflow_dispatch:

run-name: "cron"

permissions:
  contents: write
  issues: write
  actions: write

jobs:
  build-gpapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo build --manifest-path gpapi/Cargo.toml --release
      - uses: actions/upload-artifact@v6
        with:
          name: gpapi
          path: ./gpapi/target/release/gpapi

  Signal-Android:
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/cron@master
        with:
          JOB_NAME: ${{ github.job }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE: playstore
          GPAPI_EMAIL: ${{ secrets.EMAIL }}
          AAS_TOKEN: ${{ secrets.AAS_TOKEN }}
          PACKAGE: org.thoughtcrime.securesms

  Signal-Desktop:
    env:
      TYPE: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check for new version
        run: |
          VERSION=$(curl -s --fail https://api.github.com/repos/signalapp/Signal-Desktop/releases/latest | jq -r .tag_name | tr -d vV)
          if ! grep -F ">v${VERSION}<" "history/${{ github.job }}.md" >/dev/null; then
            echo "NEW_VERSION=${VERSION}" >> $GITHUB_ENV
          fi
      - name: Send Discord notification
        uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        if: ${{ env.NEW_VERSION }}
        with:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          mode: "cron"
          MESSAGE: "⚠️  ${{ github.job }} v${NEW_VERSION} (${{ env.TYPE }}) not already checked"
      - name: Create issue and run workflow if new version
        if: ${{ env.NEW_VERSION }}
        run: |
          title="${{ github.job }}: check v${{ env.NEW_VERSION }} (${{ env.TYPE }})"
          if ! gh issue list --search "${title}" --state open | grep -q "${title}"; then
            gh issue create --title "${title}" --body "-"
            gh workflow run "${{ github.job }}" -f VERSION=${{ env.NEW_VERSION }}
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
