name: cron

on:
  push:
    paths:
      - ".github/workflows/cron.yml"
  schedule:
    - cron: "0 3 * * *" # every day 03:00 am UTC
  workflow_dispatch:

run-name: "cron"

permissions:
  contents: write
  issues: write
  actions: write

jobs:
  build-gpapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo build --manifest-path gpapi/Cargo.toml --release
      - uses: actions/upload-artifact@v6
        with:
          name: gpapi
          path: ./gpapi/target/release/gpapi

  Signal-Android:
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/cron@master
        with:
          JOB_NAME: ${{ github.job }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPAPI_EMAIL: ${{ secrets.EMAIL }}
          AAS_TOKEN: ${{ secrets.AAS_TOKEN }}
          PACKAGE: org.thoughtcrime.securesms
          TYPE: playstore

  Telegram-Android:
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/cron@master
        with:
          JOB_NAME: ${{ github.job }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPAPI_EMAIL: ${{ secrets.EMAIL }}
          AAS_TOKEN: ${{ secrets.AAS_TOKEN }}
          TRIGGER_WORKFLOW: false
          PACKAGE: org.telegram.messenger
          TYPE: playstore

  Threema-Android:
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/cron@master
        with:
          JOB_NAME: ${{ github.job }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPAPI_EMAIL: ${{ secrets.EMAIL }}
          AAS_TOKEN: ${{ secrets.AAS_TOKEN }}
          TRIGGER_WORKFLOW: false
          PACKAGE: ch.threema.app
          TYPE: playstore

  Briar-Android:
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/cron@master
        with:
          JOB_NAME: ${{ github.job }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPAPI_EMAIL: ${{ secrets.EMAIL }}
          AAS_TOKEN: ${{ secrets.AAS_TOKEN }}
          PACKAGE: org.briarproject.briar.android
          TYPE: playstore

  Signal-Desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/cron@master
        with:
          JOB_NAME: ${{ github.job }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: signalapp/Signal-Desktop
          TYPE: github

  Molly-Android:
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/cron@master
        with:
          JOB_NAME: ${{ github.job }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: mollyim/mollyim-android
          TYPE: github
          PRE_RELEASE: true

  SimpleX-Desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/cron@master
        with:
          JOB_NAME: ${{ github.job }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: simplex-chat/simplex-chat
          TYPE: github
          PRE_RELEASE: true
