name: custom

on:
  workflow_dispatch:

run-name: "custom"

jobs:
  website-download:
    runs-on: self-hosted
    steps:
      - run: |
          set -x
          docker ps -a
          docker run hello-world
