name: download

on:
  workflow_dispatch:
    inputs:
      PACKAGE_NAME:
        description: "PACKAGE_NAME"
        required: true

run-name: "Download '${{ inputs.PACKAGE_NAME }}' apk from PlayStore"

jobs:
  build-gpapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo build --manifest-path gpapi/Cargo.toml --release
      - uses: actions/upload-artifact@v7
        with:
          name: gpapi
          path: ./gpapi/target/release/gpapi

  download:
    needs: build-gpapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: gpapi
          path: /usr/local/bin/
      - name: Download from Playstore
        run: |
          sudo chmod +x /usr/local/bin/gpapi
          gpapi --email "${{ inputs.GPAPI_EMAIL }}" --aas-token "${{ inputs.AAS_TOKEN }}" --package "${{ inputs.PACKAGE }}" --output ./out/
          VERSION=$(cat ./out/VERSION)
          VERSION_CODE=$(cat ./out/VERSION_CODE)
          echo "$VERSION"
          echo "$VERSION_CODE"
          mkdir artifacts
          find ./out/ -type f -name "*.apk" -exec mv {} artifacts/ \;
      - uses: actions/upload-artifact@v7
        with:
          name: apk
          path: ./artifacts/
