name: Olvid-Android

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

env:
  SIGNATURE_SHA256: cc83a47d8ed411468580889fb3e058b0b31e82ef812d473531b5f9cd4a88fd33

jobs:
  fdroid-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: build
        run: |
          set -x
          git clone https://github.com/olvid-io/olvid-android
          cd olvid-android
          tags=$(curl -sfL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/olvid-io/olvid-android/tags | jq -r .[].name)
          TAG=$(echo "$tags" | grep -F "v${{ inputs.VERSION }}" | grep "fdroid" || true)
          if [ -z "$TAG" ]; then
            TAG=$(echo "$tags" | grep -F "v${{ inputs.VERSION }}")
          fi
          VERSION_CODE="$(echo "$TAG" | cut -d- -f1 | cut -d_ -f2)"
          echo "TAG: $TAG"
          echo "Version code: $VERSION_CODE"
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_OUTPUT
          git checkout "$TAG"
      - name: Build fdroid apk
        run: |
          docker build -t olvid-android ./olvid-android/reproducible-builds/
          docker run --rm --pull=never -v "$(pwd)/olvid-android/":/olvid -w /olvid/obv_messenger olvid-android ./gradlew assembleProdZfdroidRelease
      - run: find . -name "*.apk"
      - name: Download fdroid apk
        run: |
          # the trailing '02' means arm64-v8a for fdroid
          curl -L "https://f-droid.org/repo/io.olvid.messenger.nogoogle_${{ env.VERSION_CODE }}02.apk" -o fdroid-arm64-v8a.apk
      - name: Verify
        run: |
          zip -d fdroid-arm64-v8a.apk META-INF/FDROID.SF META-INF/FDROID.RSA META-INF/MANIFEST.MF
          pip install uv
          git clone https://github.com/signalapp/Signal-Android --depth 1
          cd Signal-Android/reproducible-builds/apkdiff
          uv sync
          uv run apkdiff.py ../../../fdroid-arm64-v8a.apk ../../../olvid-android/obv_messenger/app/build/outputs/apk/prodZfdroid/release/app-prod-zfdroid-arm64-v8a-release-unsigned.apk
    outputs:
      VERSION_CODE: ${{ steps.build.outputs.VERSION_CODE }}

  playstore-verify:
    runs-on: ubuntu-latest
    needs: [fdroid-verify]
    if: always() && needs.fdroid-verify.outputs.VERSION_CODE != ''
    steps:
      - uses: actions/checkout@v6
      - name: aapt
        run: echo "PATH=$PATH:/usr/local/lib/android/sdk/build-tools/37.0.0" >> $GITHUB_ENV
      - name: Download playstore apk
        run: |
          if [ "${{ needs.fdroid-verify.outputs.VERSION_CODE }}" != "" ]; then
            VERSION_CODE="${{ needs.fdroid-verify.outputs.VERSION_CODE }}"
          else
            VERSION_CODE="${{ inputs.VERSION_CODE }}"
          fi

          cargo build --manifest-path gpapi/Cargo.toml --release
          ./gpapi/target/release/gpapi --email "${{ secrets.EMAIL }}" --aas-token "${{ secrets.AAS_TOKEN }}" --package "io.olvid.messenger" --version-code ${VERSION_CODE} --output=./playstore-official/ --download

          AAPT_BADGING=$(aapt dump badging ./playstore-official/io.olvid.messenger/io.olvid.messenger.apk)
          PLAYSTORE_VERSION=$(echo "$AAPT_BADGING" | grep -o "versionName='[^']*'" | cut -d"'" -f2)
          if [[ "${{ inputs.VERSION }}" == "$PLAYSTORE_VERSION" ]]; then
            echo "✅ Versions $PLAYSTORE_VERSION match"
          else
            echo "❌ Versions differ: expected ${{ inputs.VERSION }} but got $PLAYSTORE_VERSION"
            exit 1
          fi
          apksigner verify -v --print-certs --min-sdk-version 24 ./playstore-official/io.olvid.messenger/io.olvid.messenger.apk | grep $SIGNATURE_SHA256
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: playstore-official
          path: ./playstore-official/
      - name: Build playstore apk
        run: |
          git clone https://github.com/olvid-io/olvid-android
          cd olvid-android
          tags=$(curl -sfL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/olvid-io/olvid-android/tags | jq -r .[].name)
          TAG=$(echo "$tags" | grep -F "v${{ inputs.VERSION }}" | grep "fdroid")
          if [ -z "$TAG" ]; then
            TAG=$(echo "$tags" | grep -F "v${{ inputs.VERSION }}")
          fi
          git checkout "$TAG"
          docker build -t olvid-android ./reproducible-builds/
          docker run --rm --pull=never -v "$(pwd)":/olvid -w /olvid/obv_messenger olvid-android ./gradlew bundleProdFullRelease
          curl -L https://github.com/google/bundletool/releases/download/1.18.3/bundletool-all-1.18.3.jar -o bundletool.jar
          java -jar bundletool.jar build-apks --bundle=./obv_messenger/app/build/outputs/bundle/prodFullRelease/app-prod-full-release.aab --output-format=DIRECTORY --output=apks
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: playstore-build
          path: olvid-android/apks/splits/
      - name: Apkdiff
        run: |
          git clone https://github.com/signalapp/Signal-Android --depth 1 apkdiff
          pip install uv
          cd apkdiff/reproducible-builds/apkdiff
          uv sync
          uv run apkdiff.py ../../../playstore-official/io.olvid.messenger/io.olvid.messenger.apk ../../../olvid-android/apks/splits/base-master.apk
          uv run apkdiff.py ../../../playstore-official/io.olvid.messenger/io.olvid.messenger.config.arm64_v8a.apk ../../../olvid-android/apks/splits/base-arm64_v8a.apk
          uv run apkdiff.py ../../../playstore-official/io.olvid.messenger/io.olvid.messenger.config.xxhdpi.apk ../../../olvid-android/apks/splits/base-xxhdpi.apk

  notify:
    needs: [fdroid-verify, playstore-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
