name: SimpleX-Desktop

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

jobs:
  linux-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        uses: BarbossHack/reproducible/.github/actions/free-up-github-action@master
      - name: Build
        run: |
          curl -LO "https://raw.githubusercontent.com/simplex-chat/simplex-chat/refs/tags/v${{ inputs.VERSION }}/scripts/simplex-chat-reproduce-builds.sh"
          chmod +x simplex-chat-reproduce-builds.sh
          ./simplex-chat-reproduce-builds.sh "v${{ inputs.VERSION }}"
      - name: Check sha256sums
        run: |
          if [ -f "v${{ inputs.VERSION }}-simplex-chat/_sha256sums" ]; then
            echo "Reproducible"
            exit 0
          else
            echo "Not reproducible"
            exit 1
          fi
      - name: Print hashes
        if: ${{ always() }}
        run: |
          echo "sha256 from-source"
          sha256sum ./v${{ inputs.VERSION }}-simplex-chat/from-source/*
          echo "sha256 prebuilt"
          sha256sum ./v${{ inputs.VERSION }}-simplex-chat/prebuilt/*
      - name: Diffoscope
        if: ${{ always() }}
        run: |
          for file in ./v${{ inputs.VERSION }}-simplex-chat/prebuilt/*; do
            filename=$(basename "$file")
            docker run --rm -w $(pwd) -v $(pwd):$(pwd) registry.salsa.debian.org/reproducible-builds/diffoscope --no-progress "v${{ inputs.VERSION }}-simplex-chat/from-source/$filename" "v${{ inputs.VERSION }}-simplex-chat/prebuilt/$filename" || true
          done

  notify:
    needs: [linux-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
