name: Telegram-Android

# https://web.telegram.org/k/#@TAndroidAPK

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

env:
  SIGNATURE_SHA256: 49c1522548ebacd46ce322b6fd47f6092bb745d0f88082145caf35e14dcc38e1

jobs:
  official:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: |
          curl -L "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Telegram-Android/${{ inputs.VERSION }}.apk" -o Telegram.apk
          AAPT_BADGING=$(/usr/local/lib/android/sdk/build-tools/36.1.0/aapt dump badging Telegram.apk)
          VERSION_CODE=$(echo "$AAPT_BADGING" | grep -o "versionCode='[^']*'" | cut -d"'" -f2)
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          /usr/local/lib/android/sdk/build-tools/36.1.0/apksigner verify -v --print-certs --min-sdk-version 24 Telegram.apk | grep $SIGNATURE_SHA256
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Telegram.apk
          path: Telegram.apk

  build:
    runs-on: ubuntu-latest
    needs: [official]
    steps:
      - name: Free up disk space
        uses: BarbossHack/reproducible/.github/actions/free-up-github-action@master
      - name: Clone
        run: |
          git clone https://github.com/DrKLO/Telegram
          cd Telegram
          git checkout $(git log --all --grep="${{ env.VERSION }}" -n 1 --format="%H")
      - name: Dockerfile
        run: |
          cd Telegram
          docker build -t telegram-build .
      - name: Build
        run: |
          cd Telegram
          docker run --rm -v "$PWD":/home/gradle:Z -w /home/gradle telegram-build gradle :TMessagesProj_AppStandalone:assembleAfatStandalone
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Telegram-${{ env.VERSION }}.apk
          path: ./Telegram/TMessagesProj_AppStandalone/build/outputs/apk/afat/standalone/app.apk

  diff:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: Telegram.apk
          path: official
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: Telegram-${{ env.VERSION }}.apk
          path: build
      - name: Signal Apkdiff
        continue-on-error: true
        run: |
          pip install uv
          git clone https://github.com/signalapp/Signal-Android --depth 1
          cd Signal-Android/reproducible-builds/apkdiff
          uv sync
          zip -d ../../../Telegram.apk "META-INF/*"
          zip -d ../../../Telegram-${{ env.VERSION }}.apk "META-INF/*"
          uv run apkdiff.py ../../../Telegram.apk ../../../Telegram-${{ env.VERSION }}.apk
      - name: apkdiff
        run: |
          curl https://raw.githubusercontent.com/DrKLO/Telegram/refs/heads/master/apkdiff.py -o apkdiff.py
          # see https://github.com/DrKLO/Telegram/pull/1899
          sed -i 's|"META-INF/CERT.SF"]|"META-INF/CERT.SF", "META-INF/version-control-info.textproto"]|g' apkdiff.py
          output=$(python apkdiff.py ./official/Telegram.apk ./build/app.apk)
          echo "$output"
          echo "$output" | grep -F "APKs are the same"
