name: Telegram-iOS

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

jobs:
  applestore-verify:
    runs-on: macos-26
    steps:
      - name: Download AppleStore IPA
        run: curl -sL --fail "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Telegram-iOS/ph.telegra.Telegraph_${{ inputs.VERSION }}.decrypted.ipa" -o Telegram-appstore.ipa
      - name: build
        run: |
          set -x

          curl -L "https://alt-eu-central-1-12.transferxl-download.com/m-euc1-11/0901eb6beb2ead087dd73db0ad174f87-0.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=VRUC2IB382WVAN635LVP%2F20260607%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260607T132006Z&X-Amz-Expires=900&X-Amz-Signature=715fd6b76d7b8641d32e2376ab114fa4ed43f12e27cbc26d0eff17b1c32e03f9&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22TransferXL-08VKqd7HHD9Gg.zip%22" -o xc.zip
          rm -rf /Applications/Xcode*
          unzip xc.zip
          rm -f xc.zip
          unxip Xcode_26.2_Release_Candidate_Apple_silicon.xip /Applications/
          rm -f Xcode_26.2_Release_Candidate_Apple_silicon.xip

          echo DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer >> "$GITHUB_ENV"
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

          xcodebuild -downloadComponent MetalToolchain || xcodebuild -downloadComponent MetalToolchain


          cd /Users/Shared/
          git clone --depth 1 --recursive https://github.com/TelegramMessenger/telegram-ios -b release-${{ inputs.VERSION }}
          cd Telegram-iOS
          XCODE_VERSION=$(cat versions.json | jq -r .xcode)
          VERSION_CODE=$(($(cat build_number_offset)+$(git rev-list --count HEAD)))

          # rm -rf /Applications/Xcode.app
          # ditto /Applications/Xcode_${XCODE_VERSION}.app /Applications/Xcode.app
          # rm -rf /Applications/Xcode_*
          # echo DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer >> "$GITHUB_ENV"
          # sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          echo "startup --output_user_root=/private/var/tmp/_bazel_containerhost" >> ~/.bazelrc

          xcrun metal --version || true
          xcodebuild -version || true
          xcode-select -p || true

          python3 build-system/Make/ImportCertificates.py --path build-system/fake-codesigning/certs
          python3 -u build-system/Make/Make.py build --buildNumber $VERSION_CODE --configurationPath="build-system/appstore-configuration.json" --codesigningInformationPath=build-system/fake-codesigning --configuration=release_arm64 --outputBuildArtifactsPath=./build/artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: applestore-build
          path: /Users/Shared/telegram-ios/build/artifacts/Telegram.ipa
      - name: Verify reproducibility
        run: python /Users/Shared/telegram-ios/tools/ipadiff.py /Users/Shared/telegram-ios/build/artifacts/Telegram.ipa Telegram-appstore.ipa

  notify:
    needs: [applestore-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
