name: Telegram-iOS

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

jobs:
  applestore-verify:
    runs-on: macos-26
    steps:
      - name: Download AppleStore IPA
        run: curl -sL --fail "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Telegram-iOS/ph.telegra.Telegraph_${{ inputs.VERSION }}.decrypted.ipa" -o Telegram-appstore.ipa
      - name: build
        run: |
          set -x

          # Build in canonical path used by Telegram
          cd /Users/Shared/

          git clone --depth 1 --recursive https://github.com/TelegramMessenger/telegram-ios -b release-${{ inputs.VERSION }}
          cd Telegram-iOS
          XCODE_VERSION=$(cat versions.json | jq -r .xcode)
          VERSION_CODE=$(($(cat build_number_offset)+$(git rev-list --count HEAD)))

          # Select the Xcode version used in versions.json
          rm -rf /Applications/Xcode.app
          ditto /Applications/Xcode_${XCODE_VERSION}.app /Applications/Xcode.app
          rm -rf /Applications/Xcode_*
          echo DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer >> "$GITHUB_ENV"
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

          # Set canonical path for bazel
          echo "startup --output_user_root=/private/var/tmp/_bazel_containerhost" >> ~/.bazelrc

          # Replace the MetalToolchain by the one actually used by Telegram (they should upgrade it...)
          xcodebuild -deleteComponent MetalToolchain
          sudo rm -rf /System/Library/AssetsV2/com_apple_MobileAsset_MetalToolchain/*.asset
          sudo rm -rf /private/var/run/com.apple.security.cryptexd/mnt/*
          curl -LO "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Xcode/MetalToolchain-17C48.exportedBundle.zip"
          unzip MetalToolchain-17C48.exportedBundle.zip
          rm -f MetalToolchain-17C48.exportedBundle.zip
          sed -i '' 's|<string>17C48</string>|<string>17C7003j</string>|g' ./MetalToolchain-17C48.exportedBundle/ExportMetadata.plist
          xcodebuild -importComponent MetalToolchain -importPath ./MetalToolchain-17C48.exportedBundle

          xcodebuild -importComponent MetalToolchain && sleep 1 || true
          xcrun metal --version && sleep 1 || true
          xcodebuild -version && sleep 1 || true
          xcode-select -p && sleep 1 || true

          python3 build-system/Make/ImportCertificates.py --path build-system/fake-codesigning/certs
          python3 -u build-system/Make/Make.py build --buildNumber $VERSION_CODE --configurationPath="build-system/appstore-configuration.json" --codesigningInformationPath=build-system/fake-codesigning --configuration=release_arm64 --outputBuildArtifactsPath=./build/artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: applestore-build
          path: /Users/Shared/telegram-ios/build/artifacts/Telegram.ipa
      - name: Verify reproducibility
        run: python /Users/Shared/telegram-ios/tools/ipadiff.py /Users/Shared/telegram-ios/build/artifacts/Telegram.ipa Telegram-appstore.ipa

  notify:
    needs: [applestore-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
