name: Threema-Android

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

env:
  SIGNATURE_SHA256: 269d600e1ce7e0a7ffddb18fb92251092938f5be38ea1113e29213564b32cb44

jobs:
  website-verify:
    runs-on: ubuntu-latest
    steps:
      - name: build-tools
        run: echo "PATH=/usr/local/lib/android/sdk/build-tools/37.0.0:$PATH" >> $GITHUB_ENV
      - name: Official
        id: download
        run: |
          curl -L "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Threema-Android/${{ inputs.VERSION }}.apk" -o Threema.apk
          AAPT_BADGING=$(aapt dump badging Threema.apk)
          VERSION_CODE=$(echo "$AAPT_BADGING" | grep -o "versionCode='[^']*'" | cut -d"'" -f2)
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_OUTPUT
          apksigner verify -v --print-certs Threema.apk | grep $SIGNATURE_SHA256
      - name: Dockerfile
        run: |
          git clone https://github.com/threema-ch/threema-android --depth 1 -b "${{ inputs.VERSION }}-${{ env.VERSION_CODE }}"
          cd threema-android
          rm -rf .git
          export RUST_VERSION=$(grep "channel = " "./domain/libthreema/rust-toolchain.toml" | cut -d= -f2 | xargs)
          cd scripts
          docker build --build-arg RUST_VERSION=$RUST_VERSION -t docker.io/threema/android-compile:${{ env.VERSION_CODE }} .
      - name: Build
        run: ./threema-android/scripts/build-release.sh -v threemashop_private --no-image-export --i-accept-the-android-sdk-license
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-website
          path: threema-android/release/${{ inputs.VERSION }}-${{ env.VERSION_CODE }}/threemashop_private/app-store_threema-universal-release-unsigned.apk
      - name: Apkdiff
        run: ./threema-android/scripts/verify-build.sh -n "${{ inputs.VERSION }}-${{ env.VERSION_CODE }}" -v threemashop_private -p Threema.apk
      - uses: BarbossHack/reproducible/.github/actions/apkdiff@master
        with:
          APKS_A: threema-android/release/${{ inputs.VERSION }}-${{ env.VERSION_CODE }}/threemashop_private/app-store_threema-universal-release-unsigned.apk
          APKS_B: Threema.apk
          IGNORE_FILES: |-
            META-INF/ANDROID_.RSA
            META-INF/ANDROID_.SF
    outputs:
      VERSION_CODE: ${{ steps.download.outputs.VERSION_CODE }}

  fdroid-verify:
    needs: website-verify
    if: always() && needs.website-verify.outputs.VERSION_CODE != ''
    runs-on: ubuntu-latest
    steps:
      - name: build-tools
        run: echo "PATH=/usr/local/lib/android/sdk/build-tools/37.0.0:$PATH" >> $GITHUB_ENV
      - name: Official
        run: |
          set -x
          curl -sSfL --retry 5 --retry-all-errors "https://f-droid.org/repo/ch.threema.app.libre_${{ needs.website-verify.outputs.VERSION_CODE }}.apk" -o Threema.apk
          apksigner verify -v --print-certs Threema.apk | grep $SIGNATURE_SHA256 || true # FIXME: re-enable this shit
      - name: Dockerfile
        run: |
          git clone https://github.com/threema-ch/threema-android --depth 1 -b "${{ inputs.VERSION }}-${{ env.VERSION_CODE }}"
          cd threema-android
          rm -rf .git
          export RUST_VERSION=$(grep "channel = " "./domain/libthreema/rust-toolchain.toml" | cut -d= -f2 | xargs)
          cd scripts
          docker build --build-arg RUST_VERSION=$RUST_VERSION -t docker.io/threema/android-compile:${{ env.VERSION_CODE }} .
      - name: Build
        run: ./threema-android/scripts/build-release.sh -v libre_private --no-image-export --i-accept-the-android-sdk-license
      - run: find . -name "*.apk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-fdroid
          path: threema-android/release/${{ inputs.VERSION }}-${{ env.VERSION_CODE }}/libre_private/app-store_threema-universal-release-unsigned.apk
      - name: Apkdiff
        run: ./threema-android/scripts/verify-build.sh -n "${{ inputs.VERSION }}-${{ env.VERSION_CODE }}" -v libre_private -p Threema.apk
      - uses: BarbossHack/reproducible/.github/actions/apkdiff@master
        with:
          APKS_A: threema-android/release/${{ inputs.VERSION }}-${{ env.VERSION_CODE }}/libre_private/app-store_threema-universal-release-unsigned.apk
          APKS_B: Threema.apk
          IGNORE_FILES: |-
            META-INF/ANDROID_.RSA
            META-INF/ANDROID_.SF

  playstore-verify:
    needs: website-verify
    if: always() && needs.website-verify.outputs.VERSION_CODE != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download Play Store APK
        run: |
          # See ./app/build.gradle.kts for the version code calculation
          VERSION_CODE_PLAYSTORE=$(( 3 * 1000000 + ${{ needs.website-verify.outputs.VERSION_CODE }} ))
          echo "Using version code $VERSION_CODE_PLAYSTORE for playstore download, expected to be 3 * 1000000 + ${{ needs.website-verify.outputs.VERSION_CODE }}"

          cargo build --manifest-path gpapi/Cargo.toml --release
          ./gpapi/target/release/gpapi --email "${{ secrets.EMAIL }}" --aas-token "${{ secrets.AAS_TOKEN }}" --package "ch.threema.app" --version-code ${VERSION_CODE_PLAYSTORE} --output=./playstore/ --download
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: playstore-official
          path: playstore/ch.threema.app.apk
      - name: Dockerfile
        run: |
          git clone https://github.com/threema-ch/threema-android --depth 1 -b "${{ inputs.VERSION }}-${{ needs.website-verify.outputs.VERSION_CODE }}"
          cd threema-android
          rm -rf .git
          export RUST_VERSION=$(grep "channel = " "./domain/libthreema/rust-toolchain.toml" | cut -d= -f2 | xargs)
          cd scripts
          docker build --build-arg RUST_VERSION=$RUST_VERSION -t docker.io/threema/android-compile:${{ needs.website-verify.outputs.VERSION_CODE }} .
      - name: Build
        run: ./threema-android/scripts/build-release.sh -v googleplay_private --no-image-export --i-accept-the-android-sdk-license
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: playstore-build
          path: threema-android/release/${{ inputs.VERSION }}-${{ needs.website-verify.outputs.VERSION_CODE }}/googleplay_private/app-store_google-arm64-v8a-release-unsigned.apk
      - name: Threema Verify Build
        run: ./threema-android/scripts/verify-build.sh -n "${{ inputs.VERSION }}-${{ needs.website-verify.outputs.VERSION_CODE }}" -v googleplay_private -p playstore/ch.threema.app.apk
      - uses: BarbossHack/reproducible/.github/actions/apkdiff@master
        with:
          APKS_A: threema-android/release/${{ inputs.VERSION }}-${{ needs.website-verify.outputs.VERSION_CODE }}/googleplay_private/app-store_google-arm64-v8a-release-unsigned.apk
          APKS_B: playstore/ch.threema.app.apk
          IGNORE_FILES: |-
            META-INF/ANDROID_.RSA
            META-INF/ANDROID_.SF

  notify:
    needs: [website-verify, playstore-verify, fdroid-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
