name: Threema-Android

# https://shop.threema.ch/fr/download

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

env:
  SIGNATURE_SHA256: 269d600e1ce7e0a7ffddb18fb92251092938f5be38ea1113e29213564b32cb44

jobs:
  website-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Official
        run: |
          curl -L "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Threema-Android/${{ inputs.VERSION }}.apk" -o Threema.apk
          AAPT_BADGING=$(/usr/local/lib/android/sdk/build-tools/36.1.0/aapt dump badging Threema.apk)
          VERSION_CODE=$(echo "$AAPT_BADGING" | grep -o "versionCode='[^']*'" | cut -d"'" -f2)
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          /usr/local/lib/android/sdk/build-tools/36.1.0/apksigner verify -v --print-certs --min-sdk-version 24 Threema.apk | grep $SIGNATURE_SHA256
      - name: Dockerfile
        run: |
          git clone https://github.com/threema-ch/threema-android --depth 1 -b "${{ inputs.VERSION }}-${{ env.VERSION_CODE }}"
          cd threema-android
          export RUST_VERSION=$(grep "channel = " "./domain/libthreema/rust-toolchain.toml" | cut -d= -f2 | xargs)
          cd scripts
          docker build --build-arg RUST_VERSION=$RUST_VERSION -t docker.io/threema/android-compile:${{ env.VERSION_CODE }} .
      - name: Build
        run: |
          ./threema-android/scripts/build-release.sh -v threemashop_private --no-image-export --i-accept-the-android-sdk-license
          ls -Rlsah threema-android/release
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-website
          path: threema-android/release/${{ inputs.VERSION }}-${{ env.VERSION_CODE }}/threemashop_private/app-store_threema-universal-release-unsigned.apk
      - name: Apkdiff
        run: |
          ./threema-android/scripts/verify-build.sh -n "${{ inputs.VERSION }}-${{ env.VERSION_CODE }}" -v threemashop_private -p Threema.apk
      - name: Signal Apkdiff
        run: |
          pip install uv
          git clone https://github.com/signalapp/Signal-Android --depth 1
          cd Signal-Android/reproducible-builds/apkdiff
          uv sync
          zip -d ../../../Threema.apk "META-INF/*"
          zip -d ../../../threema-android/release/${{ inputs.VERSION }}-${{ env.VERSION_CODE }}/threemashop_private/app-store_threema-universal-release-unsigned.apk "META-INF/*"
          uv run apkdiff.py ../../../Threema.apk ../../../threema-android/release/${{ inputs.VERSION }}-${{ env.VERSION_CODE }}/threemashop_private/app-store_threema-universal-release-unsigned.apk

  notify:
    needs: [website-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
